stages:
  - build
  - test
  - deploy
      
job 0:
  stage: .pre
  script: /scripts/beforebuild.sh
    
job 1:
  stage: build
  script: /scripts/build.sh
        
job 2:
  stage: test
  script: cd /app && php artisan test

job 3:
  stage: test
  script: cd /app && php artisan dusk
    
job 4:
  stage: deploy
  script: echo 'make deploy'
  
job 5:
  stage: .post
  script: /scripts/postbuild.sh
