concurrent = 1
check_interval = 0

[session_server]
  listen_address = "[::]:8093"
  session_timeout = 1800

[[runners]]
  name = "laravel-stage"
  url = "https://git.private.site"
  token = "your gitlab runner token for project. Run gitlab-runner register"
  executor = "shell"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
